### ISSUE TITLE
Invariant Violation: requireNativeComponent: "PTRKeyframesView" was not found in the UIManager

### ISSUE THREAD

**Issue by lucasriondel** [ptomasroos/react-native-keyframes#2]
Error found in PTRKeyframesView at Keyframes.js:24

I am using android and RN 0.57.0-rc.0, React 16.4.2.

**Comment by ptomasroos** [comment]
Did you setup the native library?

**Comment by lucasriondel** [comment]
I have set `compile 'com.facebook.keyframes:keyframes:1.0'` under `dependencies` in my `app/build.gradle` file. Is there something else i should do ?

**Comment by ptomasroos** [comment]
Feel free to check out the example project in this repo.

https://github.com/ptomasroos/react-native-keyframes/blob/master/examples/Basic/android/settings.gradle

https://github.com/ptomasroos/react-native-keyframes/blob/master/examples/Basic/android/app/build.gradle#L144

**Comment by lucasriondel** [comment]
I've done everything like the example project, but I have this error : 

```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.facebookincubator:Keyframes:eaa06f6f01.
     Required by:
         project :app > project :react-native-keyframes
```

**Comment by ptomasroos** [comment]
Please post a repo online with the error otherwise Its very hard in order for me to help out.

**Comment by ptomasroos** [comment]
Most likely you're missing this https://github.com/ptomasroos/react-native-keyframes/blob/master/android/build.gradle#L22

**Comment by lucasriondel** [comment]
Thanks, we're going forward. This is my next issue: 

```
\node_modules\@ptomasroos\react-native-keyframes\android\src\main\java\com\PTR\Keyframes\KeyframesPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: \node_modules\@ptomasroos\react-native-keyframes\android\src\main\java\com\PTR\Keyframes\KeyframesViewManager.java uses unchecked or unsafe operations.
```

**Comment by lucasriondel** [comment]
I am sorry, I cannot post a repository, I am making an app for a client and I cannot share the code..

**Comment by ptomasroos** [comment]
Too bad, if you can't help me why should I help you?
You can always create a new repo in order to have a example which is working. Its not really fair of you to think I should support you without you giving effort in making it easier for me to help you out right?

Think twice.

You can use the latest version from github in order to resolve that since the override was removed in previous RN update and its not published to npm.

"@ptomasroos/react-native-keyframes": "ptomasroos/react-native-keyframes#a5bf4908f270631928b51922921009e7dec1a7b7",

**Comment by lucasriondel** [comment]
It's not working.

I am trying to make your repository better by providing issues that exists. I am helping you and you are helping me. 

I am not forcing you to anything, just say you don't want to help and i'll use the other keyframe solution.

**Comment by ptomasroos** [comment]
You need to remove your node_modules and npm install again (or yarn), when you've changed the package.json

If you could provide a repository to where it does not work I would have solved this already and you would have been very happy having it running! So win win

**Comment by lucasriondel** [comment]
I have not changed my package.json directly, i have runned `yarn add https://github.com/ptomasroos/react-native-keyframes#a5bf4908f270631928b51922921009e7dec1a7b7`.

**Comment by ptomasroos** [comment]
Can you then paste, 

cat node_modules/@ptomasroos/react-native-keyframes/android/src/main/java/com/PTR/Keyframes/KeyframesPackage.java

**Comment by lucasriondel** [comment]
```
package com.PTR.Keyframes;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class KeyframesPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Arrays.<ViewManager>asList(new KeyframesViewManager());
    }
}
```

**Comment by ptomasroos** [comment]
Sorry impossible to figure out. Feel free to extract the code into a new repository so I can take a look and help you out if you're still looking for help.
